dist: xenial
language: ruby
services: postgresql
cache: bundler
before_script:
  - gem update --system
  - gem install bundler
  - bundle exec rails db:create
  - bundle exec rails db:migrate
deploy:
  provider: heroku
  app: resume-revision
  api_key:
    secure: Kxgv/VEIgK540BePmJR74Q3NEW628C41PvriWTlm9wlHD2D8b2wKwDZ6HuS7e1hCZ9V6jmBzJOmZO/kdXSc+zh1+P8CjuD4XjdfO4D7o63+UBdCvqjD502YzkQxrL2ZjAtjvCtdCiFP6KRgJjPzvUdgBjfVaEWGoX+kkxygzOAWRJ+cvITa2I9D3aFqMZEzYK/i83e610PUY5GIEu16ahUUPG6obdbWDpCzxfjmStXEgcT8s+Ga5NjA6Y5fjbPQNr1D0uOTP5BddH3FywdVv2O/COsdc77vMHBVQk/LQz+Izg5+Znna4XEvREkAMbRPY+v0zKOgVez9hI6vhS/PGgea9X/snVrtIetuNZHMG8aGt2Ia3Uke2VXUk5UbiCl/cMK2FV0bGdzVuuQXxaXD1iu+siwOjUCS1qjSEUk79gJ0sUeSCMwUPWtywYUzxGBhzFBrI8Wm9QgVAef979CvBDLbH/6sZ9Rv2EDQxCVRCaljau/fv1RVbUd+k996S6tfRbUg1MKsDyEI/swBIroKAiZOEEbZMnyYK3AckIis2rAUO0BVEAQx9VCHz7oNtOFvJ0ndhBjdgilf1Kd8UJkyfe9HeIgVH9UnEpan/+lXxBnFyuJ99WbcgeUMlZQdbQfP+cm38ludyQ0XyvOkCASHg+fXNQuuRkqPPEFH0z78MKJc=
  on:
    repo: scrum-gang/resume-revision
