dist: xenial
language: ruby
services: postgresql
cache: bundler
before_script:
  - gem update --system
  - gem install bundler
  - bundle exec rails db:create
  - bundle exec rails db:migrate
deploy:
  provider: heroku
  app: resume-revision
  api_key:
    secure: 3Njntpsw7Qa3pwKuMNbClpf92u67t+wk7GfpauvEKIVi2Th35QPjTYD4U1AlrgreC/BuM07wUEteBjr0Jg97tmG5PlJODaa2nLpc2jGJUmfh5ZQ19kvWbI1reKy79Hus6rFBEf2pxloysOwJec6SGi1QyJovCJj8U4qZs0WsBQtBcbWGx7uthf5rvumOuYsn7kTiOiRnLNBfQNukD3FFHwTMhHPzU1KkIMF44gy/aMyiN58TOpL7OxPfm9XSB5AeV8x2F6+n7ndiASoSEXPZ5/y14u/PIxpyKHX7NQQXBeslqU3YvfuGHXTrk/JNP91Fbw1oM1cLb3g8RyUBh42VKDNJaMh+E9mnTN+SWDdAxSqHF9nVdmg7IRULNl6w92pCLWdx0IEzQyDNX7ht/6yh5OSe3nZC0Gz80N7A/aefwy125oPRxMTk98S2Uk9Lc+02blh7hgTPjUOP1EV0nnIABtMYH+2m8prpD2DX+24buLZqVn2ZwI5LGsNSSYoASx+WVFRVFko1+13wHT+QOcJYB3O0BGHwNWkktsWXPWm6t9WhuwTm7VXXaVAd8LOia/VuAIeZii9ZiUW7kR5J8S0HTl/Ya7sh41K3ZwtDwBmgIISaPNJSjeGelygCNS6IzsSc09MNzFirjmUChz7hGzeLguIdsPJUicJmTNIzF0kmhNY=
  on:
    repo: scrum-gang/resume-revision
