dist: xenial
language: ruby
services: postgresql
cache: bundler
before_script:
  - gem update --system
  - gem install bundler
  - bundle exec rails db:create
  - bundle exec rails db:migrate
deploy:
  provider: heroku
  app: resume-revision
  api_key:
    secure: a+zmLx1iiow3egfyjeS5pLVXUeNV+Kaz0jpq/5GQbreKRw0AK5sipZ2u47ha80kY3kUZ7wKNyh8gacPHrqkLH8+bqzZK7mvOOIZxUsV18WSfYqzLZHtKcnmKCAEHMEmhvemBSvhxUuqSjcSe0vkSZd3zoJ53IfMqNcJNaBkLzMtjRdBp5hIVXZmG0ETxg6Jv9Yc5FWcHI99mCSOq7Fd7+8VLIWQvjELLx2VYhlljLHZb2EjQPZ+Q3ZHemsr0tZBXcqec09lSV1o7j1ppSj5020xL8JDOHWCjLP5D3DQSt+ltJb19eC2FvfD4BdlM3+riwdZRnMVxZYHAL+ZTjeiz3Lt+5G5B4rxSYuHkGVqElZMiIDnDC1D45Eb58CubUt23znoRFUCtIxmaXurIEdiqiPIqkcaO2zRo+DD+gdSXwWm7DP1xldG7CZoDGoYNGE1aYxKI/iDEWCbjAQMtY47nrKyMHVQclRjwZV+RySM1Jhh2kENihBj//Uuzz2vb/6QFUAZZQr0CtuwHn4VHdNcl0PKabZGNo/xJuyjDMG+dxSV+qtyaxAiySMdtyxloaXsjHh79WNlZppZnkqCCwA1tA098zEinl1I+D5NSc0qKthEZYmB0Ul69aCq61DLP/1mH7avgbtVvOhi+VHXDShsgOImjGBl9B5rl+/tyH1DG5JM=
  on:
    repo: scrum-gang/resume-revision
