default: &default
  adapter: postgresql
  template: template0
  encoding: unicode
  timeout: 5000
  pool: 5


local: &local
  username: postgres
  password: postgres
  host: localhost


development:
  <<: *default
  <<: *local
  database: resume_revision_development


test:
  <<: *default
  <<: *local
  database: resume_revision_test


production:
  <<: *default
