development: &default
  host: localhost
  adapter: postgresql
  database: resume_revision_development
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres
  template: template0
  timeout: 5000


test:
  <<: *default
  database: resume_revision_test


production:
  <<: *default
  database: resume_revision_production
  username: myapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
